repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      - id: ruff
        name: Ruff Linter (Backend)
        files: ^backend/
        args: ["--fix", "--config", "backend/pyproject.toml"]
      - id: ruff-format
        name: Ruff Formatter (Backend)
        files: ^backend/
        args: ["--config", "backend/pyproject.toml"]
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.54
    hooks:
      - id: ty
        name: Ty Linter (Backend)
        files: ^backend/
        args: ["--project", "backend"]
