version: "3.2"

services:
  redis:
    container_name: redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
    networks:
      db-net:
        aliases:
          - redis
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: divorcepredictor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      db-net:
        aliases:
          - postgres
  backend:
    container_name: backend
    restart: always
    command : bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/settings.ini
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      db-net:
        aliases:
          - backend
  frontend:
    container_name: frontend
    restart: always
    command : npm start
    environment:
      REACT_APP_API_URL: http://localhost:8000/
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      db-net:
        aliases:
          - frontend

networks:
  db-net:
    driver: bridge
